export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            width: "100%",
            background: "#222",
            color: "#fff",
            padding: "1rem 0",
            textAlign: "center",
            fontSize: "2rem",
            letterSpacing: "2px",
            fontWeight: "bold",
            marginBottom: "2rem",
          }}
        >
          Game Reviews
        </header>
        {children}
      </body>
    </html>
  );
}
